create table public.lbc_branches (id bigint generated by default as identity primary key, branch_name text not null, branch_address text not null, province text, source_url text not null, verified_at timestamptz not null default now());
create index lbc_branches_search on public.lbc_branches using gin (to_tsvector('simple', branch_name || ' ' || branch_address));
alter table public.lbc_branches enable row level security;
revoke all on public.lbc_branches from public, anon, authenticated;
grant select on public.lbc_branches to authenticated;
create policy lbc_branches_allowlisted on public.lbc_branches for select to authenticated using ((select private.is_allowed_user()));
insert into public.lbc_branches (branch_name, branch_address, province, source_url) values ('SM CITY CLARK', '199 B-2 SM Clark, McArthur Roxas St., Malabanias, Angeles City, Pampanga', 'Pampanga', 'https://www.lbcexpress.com/branches-philippines/PAMPANGA');
